### ISSUE TITLE
Замечание экзамен js

### ISSUE THREAD

**Issue by AndriiLitvin** [Mifando/Mifando.github.io#20]
1,
![image](https://cloud.githubusercontent.com/assets/13675947/13996125/09432a8a-f135-11e5-9378-1ea976b3b25e.png)
Индекс должен быть тут

2,
Сделай какой то ховер кнопкам

3,
![image](https://cloud.githubusercontent.com/assets/13675947/13996277/a41a1a6e-f135-11e5-88fa-51d55012ca21.png)
в ИЕ 8 Step и цифри повылетали с блока

4,
на ие8
![image](https://cloud.githubusercontent.com/assets/13675947/13996343/dfbfecb0-f135-11e5-8b53-58ea76985070.png)
нет плитки

и тут что то материться https://validator.w3.org/nu/?doc=http%3A%2F%2Fmifando.github.io%2FGoIT%2Fmarkup%2FJavascript%2FExam%2520javascript%2Bhtml%2Findex.html

**Comment by Mifando** [comment]
ok

**Comment by Mifando** [comment]
Исправил, посмотри пожалуйста )))

**Comment by AndriiLitvin** [comment]
Зачет
