### ISSUE TITLE
Замечания по работе 5-2 cadastre

### ISSUE THREAD

**Issue by AndriiLitvin** [Mifando/Mifando.github.io#4]
## http://joxi.ru/VrwlE7qFKVRLPm

1) При скроле улетает меню вправо.добавь контейнер и выровняй по центру а внутри должен быть весь контент хедера
2) подправь кнопку

**Comment by Mifando** [comment]
ок, сегодня переделаю

**Comment by Mifando** [comment]
исправил:
1)Выровнял по центру
2)Подправил кнопку

**Comment by AndriiLitvin** [comment]
Зачет
