### ISSUE TITLE
Замечания по экзамену 7-9

### ISSUE THREAD

**Issue by AndriiLitvin** [Mifando/Mifando.github.io#8]
## Экран 960 http://joxi.ru/vAWZzP3skqYZe2 мозила

1) сделай в логотипа маргин в процентах либо меньше тогда все станет на место
2)уберешь первое пропадет и это
3)там еще бордер

+у тебя в коде повторяются одни и те же медиаквери. там можно задавать так 
экран 320 @media(min-width: 479px)
экран 480 @media(min-width: 767px)
экран 768 @media(min-width: 959px)
экран 960 @media(max-width: 960px)

либо так  как в статье http://habrahabr.ru/post/119127/

и все свойства вкидываешь в один медиа квери чтоб не повторялось условие.
и так можно @media (min-width: 768px) and (max-width: 979px)

когда наводишь на вот эту область http://joxi.ru/J2blgP1F4G8NPr то выпадает менюшка, нужно чтоб только при наведении  на Home

**Comment by Mifando** [comment]
Ок

**Comment by AndriiLitvin** [comment]
1) http://joxi.ru/a2XQzB3Hyp5WaA уклон в другую сторону
2) http://joxi.ru/vAWZzP3skRQZ52 (экран 768) там меньше ширина и вообще для резины используй проценты там у тебя родительский блок в пикселях а внутри еще ширина в пикселях задай 100% и все норм будет. текст который там вылезет можно скрывать или обрезать.
3) http://joxi.ru/L21b6x0F6DyQDA (Экран 320) тут выровняй заголовок по левому краю.

А в целом выглядит хорошо. Доделывай и будет Зачет)

**Comment by Mifando** [comment]
Ура,ок доделаю)))

**Comment by AndriiLitvin** [comment]
http://joxi.ru/823pdlkF6KnNJA - там тени нет
В общем поправь) Зачет

**Comment by Mifando** [comment]
ого, втыкнул немного...исправил))
